language: node_js
node_js:
  - 8.11.3
before_install:
  - export CHROME_BIN=/usr/bin/google-chrome
  - export DISPLAY=:99.0
services:
  - xvfb
script:
  - cd dist
  - zip -r babylon-runtime-$TRAVIS_TAG.zip .
  - cd ..
  - node ./tools/npm-publish/prebuildpackage.js
  - cd dist.npm
deploy:
  - provider: npm
    email: "fabien.levavasseur@gmail.com"
    api_key: $NPM_AUTH_TOKEN
    skip_cleanup: true
    on:
      tags: true
  - provider: releases
    api_key: $GITHUB_OAUTH_TOKEN
    file:
      - '_r.js'
      - '_r.js.map'
      - '_r.min.js'
      - '_r.min.js.map'
      - '../dist/babylon-runtime-${TRAVIS_TAG}.zip'
    skip_cleanup: true
    on:
      tags: true
after_deploy:
  - cd ..
  - chmod +x ./tools/discord-bot/discord-new-release.sh
  - ./tools/discord-bot/discord-new-release.sh success $WEBHOOK_URL
after_failure:
  - wget https://raw.githubusercontent.com/DiscordHooks/travis-ci-discord-webhook/master/send.sh
  - chmod +x send.sh
  - ./send.sh failure $WEBHOOK_URL
