language: node_js
node_js:
  - 8.11.3
before_install:
  - export CHROME_BIN=/usr/bin/google-chrome
  - export DISPLAY=:99.0
services:
  - xvfb
script:
  - echo "Deploying to Github Releases..."
deploy:
    provider: releases
    api_key: $GITHUB_OAUTH_TOKEN
    file:
      - 'dist/_r.js'
      - 'dist/_r.js.map'
      - 'dist/_r.min.js'
      - 'dist/_r.min.js.map'
    skip_cleanup: true
    on:
      tags: true