language: node_js
node_js:
  - 8.11.3
before_install:
  - export CHROME_BIN=/usr/bin/google-chrome
  - export DISPLAY=:99.0
services:
  - xvfb
script:
  - cd dist
  - zip -r babylon-runtime-$TRAVIS_TAG.zip .
  - ls
  - cd ..
before_deploy:
  - node tools/npm-publish/prebuildpackage.js
  - cd dist.npm
  - ls
deploy:
  provider: npm
  email: "fabien.levavasseur@gmail.com"
  api_key: $NPM_AUTH_TOKEN
  skip_cleanup: true
  on:
    tags: true
after_deploy:
  -  cd ..
